# This workflow will build Javadoc and pitest reports

name: Documentation workflow

on:
  push:
    branches: [ master ]

jobs:
  documentation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Javadoc generation
        run: mvn package -DskipTests=true -P javadoc --file pom.xml
      - name: Mutation testing
        run: mvn install -DskipTests=true -P mutation --file pom.xml
      - name: Prepare documentation
        run: |
          cp -R target/site build
          cp -R iextrading4j-mutation/target/pit-reports build/pit-reports
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

